require("plugin_config.lsp")
require("plugin_config.telescopeconfig")
require("plugin_config.nerdTree")
require("plugin_config.vim-airline")
require("plugin_config.nvim_tree")
require("plugin_config.nvim-autopairs")
